// Code generated by qtc from "contactpage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line templates/contactpage.qtpl:3
package templates

//line templates/contactpage.qtpl:3
import "github.com/valyala/fasthttp"

//line templates/contactpage.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/contactpage.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/contactpage.qtpl:6
type ContactPage struct {
	CTX *fasthttp.RequestCtx
}

//line templates/contactpage.qtpl:12
func (p *ContactPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/contactpage.qtpl:12
	qw422016.N().S(`
	CONTACTO TITULO
`)
//line templates/contactpage.qtpl:14
}

//line templates/contactpage.qtpl:14
func (p *ContactPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/contactpage.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/contactpage.qtpl:14
	p.StreamTitle(qw422016)
//line templates/contactpage.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line templates/contactpage.qtpl:14
}

//line templates/contactpage.qtpl:14
func (p *ContactPage) Title() string {
//line templates/contactpage.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/contactpage.qtpl:14
	p.WriteTitle(qb422016)
//line templates/contactpage.qtpl:14
	qs422016 := string(qb422016.B)
//line templates/contactpage.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/contactpage.qtpl:14
	return qs422016
//line templates/contactpage.qtpl:14
}

//line templates/contactpage.qtpl:17
func (p *ContactPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/contactpage.qtpl:17
	qw422016.N().S(`
	<h1>BODY DESDE CONTACTO</h1>

`)
//line templates/contactpage.qtpl:20
}

//line templates/contactpage.qtpl:20
func (p *ContactPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/contactpage.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/contactpage.qtpl:20
	p.StreamBody(qw422016)
//line templates/contactpage.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line templates/contactpage.qtpl:20
}

//line templates/contactpage.qtpl:20
func (p *ContactPage) Body() string {
//line templates/contactpage.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/contactpage.qtpl:20
	p.WriteBody(qb422016)
//line templates/contactpage.qtpl:20
	qs422016 := string(qb422016.B)
//line templates/contactpage.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/contactpage.qtpl:20
	return qs422016
//line templates/contactpage.qtpl:20
}

//line templates/contactpage.qtpl:22
func (p *ContactPage) StreamUserInfo(qw422016 *qt422016.Writer) {
//line templates/contactpage.qtpl:22
	qw422016.N().S(`
	<h1>**USER INFOO**</h1>
`)
//line templates/contactpage.qtpl:24
}

//line templates/contactpage.qtpl:24
func (p *ContactPage) WriteUserInfo(qq422016 qtio422016.Writer) {
//line templates/contactpage.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/contactpage.qtpl:24
	p.StreamUserInfo(qw422016)
//line templates/contactpage.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line templates/contactpage.qtpl:24
}

//line templates/contactpage.qtpl:24
func (p *ContactPage) UserInfo() string {
//line templates/contactpage.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/contactpage.qtpl:24
	p.WriteUserInfo(qb422016)
//line templates/contactpage.qtpl:24
	qs422016 := string(qb422016.B)
//line templates/contactpage.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/contactpage.qtpl:24
	return qs422016
//line templates/contactpage.qtpl:24
}
