// Code generated by qtc from "mainpage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line templates/mainpage.qtpl:3
package templates

//line templates/mainpage.qtpl:3
import "github.com/valyala/fasthttp"

//line templates/mainpage.qtpl:4
import "strings"

//line templates/mainpage.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/mainpage.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/mainpage.qtpl:7
type MainPage struct {
	CTX      *fasthttp.RequestCtx
	Products []string
}

//line templates/mainpage.qtpl:16
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:16
	qw422016.N().S(`
	Cambiamos el titulo
`)
//line templates/mainpage.qtpl:18
}

//line templates/mainpage.qtpl:18
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:18
	p.StreamTitle(qw422016)
//line templates/mainpage.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:18
}

//line templates/mainpage.qtpl:18
func (p *MainPage) Title() string {
//line templates/mainpage.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:18
	p.WriteTitle(qb422016)
//line templates/mainpage.qtpl:18
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:18
	return qs422016
//line templates/mainpage.qtpl:18
}

//line templates/mainpage.qtpl:20
func (p *MainPage) StreamFooter(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:20
	qw422016.N().S(`
	<h1>Te presento a rorolas FOOTER </h1>
`)
//line templates/mainpage.qtpl:22
}

//line templates/mainpage.qtpl:22
func (p *MainPage) WriteFooter(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:22
	p.StreamFooter(qw422016)
//line templates/mainpage.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:22
}

//line templates/mainpage.qtpl:22
func (p *MainPage) Footer() string {
//line templates/mainpage.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:22
	p.WriteFooter(qb422016)
//line templates/mainpage.qtpl:22
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:22
	return qs422016
//line templates/mainpage.qtpl:22
}

//line templates/mainpage.qtpl:25
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:25
	qw422016.N().S(`
    <br/>
    <br/>
	<div>
        `)
//line templates/mainpage.qtpl:29
	p.streamform(qw422016)
//line templates/mainpage.qtpl:29
	qw422016.N().S(`
	</div>

    <br/>

    `)
//line templates/mainpage.qtpl:34
	if len(p.Products) > 0 {
//line templates/mainpage.qtpl:34
		qw422016.N().S(`
      `)
//line templates/mainpage.qtpl:35
		p.StreamDisplayProducts(qw422016)
//line templates/mainpage.qtpl:35
		qw422016.N().S(`
    `)
//line templates/mainpage.qtpl:36
	} else {
//line templates/mainpage.qtpl:36
		qw422016.N().S(`
        `)
//line templates/mainpage.qtpl:37
		p.StreamWithoutProducts(qw422016)
//line templates/mainpage.qtpl:37
		qw422016.N().S(`
    `)
//line templates/mainpage.qtpl:38
	}
//line templates/mainpage.qtpl:38
	qw422016.N().S(`

`)
//line templates/mainpage.qtpl:40
}

//line templates/mainpage.qtpl:40
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:40
	p.StreamBody(qw422016)
//line templates/mainpage.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:40
}

//line templates/mainpage.qtpl:40
func (p *MainPage) Body() string {
//line templates/mainpage.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:40
	p.WriteBody(qb422016)
//line templates/mainpage.qtpl:40
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:40
	return qs422016
//line templates/mainpage.qtpl:40
}

//line templates/mainpage.qtpl:42
func (p *MainPage) StreamUserInfo(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:42
	qw422016.N().S(`
    <br/>
    <article class="message is-warning">
      <div class="message-header">
        <p>Por motivos de seguridad te estamos vigilando: </p>
      </div>
      <div class="message-body">
        Tu IP es: <b> `)
//line templates/mainpage.qtpl:49
	qw422016.E().S(p.CTX.RemoteIP().String())
//line templates/mainpage.qtpl:49
	qw422016.N().S(` </b><br/>
        Te estas conectando desde: <b> `)
//line templates/mainpage.qtpl:50
	qw422016.E().Z(p.CTX.UserAgent())
//line templates/mainpage.qtpl:50
	qw422016.N().S(`</b>
      </div>
    </article>
    <br/>

`)
//line templates/mainpage.qtpl:55
}

//line templates/mainpage.qtpl:55
func (p *MainPage) WriteUserInfo(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:55
	p.StreamUserInfo(qw422016)
//line templates/mainpage.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:55
}

//line templates/mainpage.qtpl:55
func (p *MainPage) UserInfo() string {
//line templates/mainpage.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:55
	p.WriteUserInfo(qb422016)
//line templates/mainpage.qtpl:55
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:55
	return qs422016
//line templates/mainpage.qtpl:55
}

//line templates/mainpage.qtpl:57
func (p *MainPage) streamform(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:57
	qw422016.N().S(`
	<form>
	<div class="field">
      <div class="control">
        <label class="label"> Ingresa un producto:</label>
        <input class="input is-success" type="text" name="product" placeholder="iphone x">
        <br>
        <button class="button is-success mt-3" type="submit"> Buscar productos </button>
      </div>
    </div>
	</form>
`)
//line templates/mainpage.qtpl:68
}

//line templates/mainpage.qtpl:68
func (p *MainPage) writeform(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:68
	p.streamform(qw422016)
//line templates/mainpage.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:68
}

//line templates/mainpage.qtpl:68
func (p *MainPage) form() string {
//line templates/mainpage.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:68
	p.writeform(qb422016)
//line templates/mainpage.qtpl:68
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:68
	return qs422016
//line templates/mainpage.qtpl:68
}

//line templates/mainpage.qtpl:70
func (p *MainPage) StreamDisplayProducts(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:70
	qw422016.N().S(`
	<div class="columns is-multiline">
            `)
//line templates/mainpage.qtpl:72
	for _, name := range p.Products {
//line templates/mainpage.qtpl:72
		qw422016.N().S(`
                `)
//line templates/mainpage.qtpl:73
		n := strings.Split(name, ":::")

//line templates/mainpage.qtpl:73
		qw422016.N().S(`
                  <div class="column is-one-quarter">
                    <div class="card">
                      <div class="card-image">
                        <figure class="image is-4by3">
                          <img src="`)
//line templates/mainpage.qtpl:78
		qw422016.E().J(n[4])
//line templates/mainpage.qtpl:78
		qw422016.N().S(`" alt="`)
//line templates/mainpage.qtpl:78
		qw422016.E().J(n[1])
//line templates/mainpage.qtpl:78
		qw422016.N().S(`">
                        </figure>
                      </div>
                      <div class="card-content">
                            <p class="title is-6">`)
//line templates/mainpage.qtpl:82
		qw422016.E().J(n[1])
//line templates/mainpage.qtpl:82
		qw422016.N().S(`</p>
                            <p class="subtitle is-6">`)
//line templates/mainpage.qtpl:83
		qw422016.E().J(n[0])
//line templates/mainpage.qtpl:83
		qw422016.N().S(`</p>
                            <hr>
                        <div class="content">
                          👉 `)
//line templates/mainpage.qtpl:86
		qw422016.E().J(n[5])
//line templates/mainpage.qtpl:86
		qw422016.N().S(` <br>
                          💵 <b>S./`)
//line templates/mainpage.qtpl:87
		qw422016.E().J(n[3])
//line templates/mainpage.qtpl:87
		qw422016.N().S(`</b> <small>soles</small><br/>
                          👁 <a href="`)
//line templates/mainpage.qtpl:88
		qw422016.E().J(n[2])
//line templates/mainpage.qtpl:88
		qw422016.N().S(`" target="_blank">Ver producto </a><br/>
                          <br>
                        </div>
                      </div>
                    </div>
                  </div>

            `)
//line templates/mainpage.qtpl:95
	}
//line templates/mainpage.qtpl:95
	qw422016.N().S(`
        </div>
`)
//line templates/mainpage.qtpl:97
}

//line templates/mainpage.qtpl:97
func (p *MainPage) WriteDisplayProducts(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:97
	p.StreamDisplayProducts(qw422016)
//line templates/mainpage.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:97
}

//line templates/mainpage.qtpl:97
func (p *MainPage) DisplayProducts() string {
//line templates/mainpage.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:97
	p.WriteDisplayProducts(qb422016)
//line templates/mainpage.qtpl:97
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:97
	return qs422016
//line templates/mainpage.qtpl:97
}

//line templates/mainpage.qtpl:99
func (p *MainPage) StreamWithoutProducts(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:99
	qw422016.N().S(`
	<h2>Selecciona un producto </h2>
`)
//line templates/mainpage.qtpl:101
}

//line templates/mainpage.qtpl:101
func (p *MainPage) WriteWithoutProducts(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:101
	p.StreamWithoutProducts(qw422016)
//line templates/mainpage.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:101
}

//line templates/mainpage.qtpl:101
func (p *MainPage) WithoutProducts() string {
//line templates/mainpage.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:101
	p.WriteWithoutProducts(qb422016)
//line templates/mainpage.qtpl:101
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:101
	return qs422016
//line templates/mainpage.qtpl:101
}
