// Code generated by qtc from "tablepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Table page template. Implements BasePage methods.
//

//line templates/tablepage.qtpl:3
package templates

//line templates/tablepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/tablepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/tablepage.qtpl:4
type TablePage struct {
	Rows []string
}

//line templates/tablepage.qtpl:9
func (p *TablePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/tablepage.qtpl:9
	qw422016.N().S(`
	This is table page
`)
//line templates/tablepage.qtpl:11
}

//line templates/tablepage.qtpl:11
func (p *TablePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/tablepage.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/tablepage.qtpl:11
	p.StreamTitle(qw422016)
//line templates/tablepage.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line templates/tablepage.qtpl:11
}

//line templates/tablepage.qtpl:11
func (p *TablePage) Title() string {
//line templates/tablepage.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/tablepage.qtpl:11
	p.WriteTitle(qb422016)
//line templates/tablepage.qtpl:11
	qs422016 := string(qb422016.B)
//line templates/tablepage.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/tablepage.qtpl:11
	return qs422016
//line templates/tablepage.qtpl:11
}

//line templates/tablepage.qtpl:14
func (p *TablePage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/tablepage.qtpl:14
	qw422016.N().S(`
	<h1>Table page</h1>

	`)
//line templates/tablepage.qtpl:17
	p.streamform(qw422016)
//line templates/tablepage.qtpl:17
	qw422016.N().S(`

	`)
//line templates/tablepage.qtpl:19
	if len(p.Rows) == 0 {
//line templates/tablepage.qtpl:19
		qw422016.N().S(`
		No rows. Click <a href="/table?rowsCount=5">here</a>.
	`)
//line templates/tablepage.qtpl:21
	} else {
//line templates/tablepage.qtpl:21
		qw422016.N().S(`
		<table>
			`)
//line templates/tablepage.qtpl:23
		streamemitRows(qw422016, p.Rows)
//line templates/tablepage.qtpl:23
		qw422016.N().S(`
		</table>
	`)
//line templates/tablepage.qtpl:25
	}
//line templates/tablepage.qtpl:25
	qw422016.N().S(`
`)
//line templates/tablepage.qtpl:26
}

//line templates/tablepage.qtpl:26
func (p *TablePage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/tablepage.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/tablepage.qtpl:26
	p.StreamBody(qw422016)
//line templates/tablepage.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line templates/tablepage.qtpl:26
}

//line templates/tablepage.qtpl:26
func (p *TablePage) Body() string {
//line templates/tablepage.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/tablepage.qtpl:26
	p.WriteBody(qb422016)
//line templates/tablepage.qtpl:26
	qs422016 := string(qb422016.B)
//line templates/tablepage.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/tablepage.qtpl:26
	return qs422016
//line templates/tablepage.qtpl:26
}

//line templates/tablepage.qtpl:28
func streamemitRows(qw422016 *qt422016.Writer, rows []string) {
//line templates/tablepage.qtpl:28
	qw422016.N().S(`
	<tr>
		<th>#</th>
		<th>value</th>
	</tr>

	`)
//line templates/tablepage.qtpl:34
	for n, r := range rows {
//line templates/tablepage.qtpl:34
		qw422016.N().S(`
		`)
//line templates/tablepage.qtpl:35
		if r == "bingo" {
//line templates/tablepage.qtpl:35
			qw422016.N().S(`
			<tr><td colspan="2"><h1>BINGO!</h1></td></tr>
			`)
//line templates/tablepage.qtpl:37
			return
//line templates/tablepage.qtpl:38
		} else if n == 42 {
//line templates/tablepage.qtpl:38
			qw422016.N().S(`
			<tr><td colspan="2">42 rows already generated</td></tr>
			`)
//line templates/tablepage.qtpl:40
			break
//line templates/tablepage.qtpl:41
		}
//line templates/tablepage.qtpl:41
		qw422016.N().S(`

		<tr style="background: `)
//line templates/tablepage.qtpl:43
		if n&1 == 1 {
//line templates/tablepage.qtpl:43
			qw422016.N().S(`white`)
//line templates/tablepage.qtpl:43
		} else {
//line templates/tablepage.qtpl:43
			qw422016.N().S(`#ddd`)
//line templates/tablepage.qtpl:43
		}
//line templates/tablepage.qtpl:43
		qw422016.N().S(`">
			<td>`)
//line templates/tablepage.qtpl:44
		qw422016.N().D(n + 1)
//line templates/tablepage.qtpl:44
		qw422016.N().S(`</td>
			<td>`)
//line templates/tablepage.qtpl:45
		qw422016.E().S(r)
//line templates/tablepage.qtpl:45
		qw422016.N().S(`</td>
		</tr>
	`)
//line templates/tablepage.qtpl:47
	}
//line templates/tablepage.qtpl:47
	qw422016.N().S(`

	<tr><td colspan="2">No bingo found</td></tr>
`)
//line templates/tablepage.qtpl:50
}

//line templates/tablepage.qtpl:50
func writeemitRows(qq422016 qtio422016.Writer, rows []string) {
//line templates/tablepage.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/tablepage.qtpl:50
	streamemitRows(qw422016, rows)
//line templates/tablepage.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line templates/tablepage.qtpl:50
}

//line templates/tablepage.qtpl:50
func emitRows(rows []string) string {
//line templates/tablepage.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/tablepage.qtpl:50
	writeemitRows(qb422016, rows)
//line templates/tablepage.qtpl:50
	qs422016 := string(qb422016.B)
//line templates/tablepage.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/tablepage.qtpl:50
	return qs422016
//line templates/tablepage.qtpl:50
}

//line templates/tablepage.qtpl:52
func (p *TablePage) streamform(qw422016 *qt422016.Writer) {
//line templates/tablepage.qtpl:52
	qw422016.N().S(`
	<form>
		Rows: <input type="text" name="rowsCount" value="`)
//line templates/tablepage.qtpl:54
	qw422016.N().D(len(p.Rows))
//line templates/tablepage.qtpl:54
	qw422016.N().S(`"/><br/>
		<input type="submit" value="Generate!"/>
	</form>
`)
//line templates/tablepage.qtpl:57
}

//line templates/tablepage.qtpl:57
func (p *TablePage) writeform(qq422016 qtio422016.Writer) {
//line templates/tablepage.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/tablepage.qtpl:57
	p.streamform(qw422016)
//line templates/tablepage.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line templates/tablepage.qtpl:57
}

//line templates/tablepage.qtpl:57
func (p *TablePage) form() string {
//line templates/tablepage.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/tablepage.qtpl:57
	p.writeform(qb422016)
//line templates/tablepage.qtpl:57
	qs422016 := string(qb422016.B)
//line templates/tablepage.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/tablepage.qtpl:57
	return qs422016
//line templates/tablepage.qtpl:57
}

//line templates/tablepage.qtpl:59
func (p *TablePage) StreamUserInfo(qw422016 *qt422016.Writer) {
//line templates/tablepage.qtpl:59
	qw422016.N().S(`
	<h1>**USER INFOO**</h1>
`)
//line templates/tablepage.qtpl:61
}

//line templates/tablepage.qtpl:61
func (p *TablePage) WriteUserInfo(qq422016 qtio422016.Writer) {
//line templates/tablepage.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/tablepage.qtpl:61
	p.StreamUserInfo(qw422016)
//line templates/tablepage.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line templates/tablepage.qtpl:61
}

//line templates/tablepage.qtpl:61
func (p *TablePage) UserInfo() string {
//line templates/tablepage.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/tablepage.qtpl:61
	p.WriteUserInfo(qb422016)
//line templates/tablepage.qtpl:61
	qs422016 := string(qb422016.B)
//line templates/tablepage.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/tablepage.qtpl:61
	return qs422016
//line templates/tablepage.qtpl:61
}
